export enum TelegrafParamtype {
  CONTEXT,
  NEXT,
  SENDER,
  MESSAGE,
  BUSINESS_CONNECTION,
  BUSINESS_MESSAGE,
  EDITED_BUSINESS_MESSAGE,
  DELETED_BUSINESS_MESSAGES,
  MESSAGE_REACTION,
  MESSAGE_REACTION_COUNT,
}
